eureka:
  instance:
    prefer-ip-address: true
    hostname: tqk-config
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://tqk-eureka:8761/eureka/